/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PROJECT NAME: PIC16F887_20MHZ
//
// PLATFORM:     mikroC for PIC18
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS                5   // Number of tasks that can be active at one time
#define OS_PRIORITY_LEVEL  OS_PRIORITY_EXTENDED 

//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------

#define OS_ENABLE_ALL               // Enable all services: CSems, QMsg, QSmsg, TTimers, DTimers
#define OS_USE_INLINE_TIMER         // Make OS_Timer service as in-line function
#define OS_TTIMERS_OPTIMIZE_SIZE    // Optimize OS_Timer code for task timers by size
#define OS_QUEUES_IDENTICAL         // Uses same functions for queues of
                                    // pointer messages and simple messages


//------------------------------------------------------------------------------
// INTERRUPT SERVICES
//------------------------------------------------------------------------------

#define OS_ENABLE_INT_CSEM
#define OS_ENABLE_INT_MSG          // Enable services for work with pointers to messages within interrupts
#define OS_ENABLE_INT_SMSG         // Enable services for work with simple messages within interrupts


//------------------------------------------------------------------------------
// TYPES
//------------------------------------------------------------------------------

#define OS_TIMER_SIZE           2   // Size of all system timers (1, 2 or 4)
#define OS_TTIMER_SIZE          2   // Size of task timers (1, 2 or 4)
#define OS_DTIMER_SIZE          2   // Size of dynamic timers (1, 2 or 4)
#define OS_QTIMER_SIZE          2   // Size of counters for queue of timers (1, 2 or 4)
#define OS_CSEM_SIZE            2   // Size of counting semaphores (1, 2 or 4)

//------------------------------------------------------------------------------
// SEMAPHORE
//------------------------------------------------------------------------------
#define OS_ENABLE_CSEM
#define OS_MSG_TYPE   const char *

#if __OSAVERSION__ >= 90200

#define OS_MSG_TYPE            unsigned char
#define OS_SMSG_TYPE           unsigned char

#else

#define OST_MSG                unsigned char*
#define OST_SMSG               unsigned char*

#endif

#endif
